"""User table modified

Revision ID: 38ab47511f80
Revises: 87558689a5fb
Create Date: 2024-02-27 08:23:52.306745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ab47511f80'
down_revision = '87558689a5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
