"""Table conver rlshps

Revision ID: 87558689a5fb
Revises: c41ba0002dd3
Create Date: 2024-02-14 17:55:19.192090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87558689a5fb'
down_revision = 'c41ba0002dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
