"""Table users rlshps

Revision ID: c41ba0002dd3
Revises: 0a49e5bfcff9
Create Date: 2024-02-14 17:44:06.150604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41ba0002dd3'
down_revision = '0a49e5bfcff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
