"""Table user updated

Revision ID: dbf1de56fb78
Revises: e4f30a66487e
Create Date: 2024-02-14 15:08:08.902951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf1de56fb78'
down_revision = 'e4f30a66487e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password_hash', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('users', '_password_hash')
    # ### end Alembic commands ###
